### ISSUE TITLE
Add a way to get the username of the bot in the TwitchChatInput

### ISSUE THREAD

**Issue by hlxid** [codeoverflow-org/chatoverflow#104]
### Description
It might be very useful to be able to get the username of the bot in the TwitchChatConnector to let a plugin ignore messages from the bot or handle them differently.

### References
This is required for https://github.com/derNiklaas/Voteban-Plugin/issues/5.

**Comment by networkException** [comment]
maybe adding an option to ignore messages send by the bot entirely should be an option

**Comment by hlxid** [comment]
Yes I think we can include that. Makes the life of plugin devs a bit easier.
