### ISSUE TITLE
Update versioning

### ISSUE THREAD

**Issue by sebinside** [codeoverflow-org/chatoverflow#118]
### Description
As mentioned in #96 we should update the version numbers of all artifacts to match the API version and follow the rules of semantic versioning (major.minor.patch).

This includes:
- API-Version (3.0)
- Framework / API Impl Version (0.3 -> 3.0)
- REST-API-Version (0.3 -> 3.0)
- GUI-Version (0.3 -> 3.0)
- npm-package version (0.3.8 -> 3.0)
- Build environment (0.3 -> 3.0)

As we distribute everything built together right now and in the (near) feature, this might solve understanding problems. To be more flexible, allowing the artefacts to change their minor and patch number while ensuring compatibility with the major number, might be still a good idea.

E.g API-Version 3.1 with GUI-Version 3.2 and npm-package 3.2.4 should still work together, as far as semantic versioning goes. `development` versions could be also tagged with `snapshot`, but this will be more interesting when we start using maven to publish.

**Comment by hlxid** [comment]
Do we want to be the patch version of the api to just be a silent version for the jar and releases or do we want to make the framework aware of it by including it in the `APIVersion` class?

**Comment by sebinside** [comment]
Closed with ea47ba6f75850869ba9d7cf8b5d86e6c68b88691.

Update the following version numbers using semantic versioning:
- API-Version (3.0.0)
- Framework / API Impl Version (3.0.0)
- GUI-Version (3.0.0)
- Build environment (3.0.0)
- Plugin Dev Environment (3.0.0, thanks @daniel0611)

The following versions have additional build number, since they are released (many times) between "official" releases:

- npm-package version (3.0.0-0)
- REST-API-Version (3.0.0-0)

Further steps (when we also use maven packages) should be discussed in alpha.
