### ISSUE TITLE
Missing Wiki entries for services 

### ISSUE THREAD

**Issue by derNiklaas** [codeoverflow-org/chatoverflow#121]
- [x] FileConnector (https://github.com/codeoverflow-org/chatoverflow/wiki/File) 
- [X] Tipeeestream (https://github.com/codeoverflow-org/chatoverflow/wiki/Tipeeestream)
- [x] Sample (https://github.com/codeoverflow-org/chatoverflow/wiki/Sample)

**Comment by J0B10** [comment]
Closed in https://github.com/codeoverflow-org/chatoverflow-wiki/commit/ecf5f55643c96ee1317ef3a27feb75e29c737291.

I don't think sample service needs an wiki entry.
