### ISSUE TITLE
Add Cheer, Raid and Host Events

### ISSUE THREAD

**Issue by hlxid** [codeoverflow-org/chatoverflow#131]
### Description
As @MelanX suggested on the discord server we should add cheer events that fire if someone cheers bits to a twitch stream.

Raid and host events also should be added.

Progress:
- [x] Tipeeestream
  - [x] Cheers
  - [x] Raids
  - [x] Hosts
  - [x] Subscription tiers and isGifted
  - [x] Superchat support
  - [x] Mention of new event types in the wiki
- [x] StreamElements(#129)
  - [x] Cheers
  - [x] Hosts
  - [x] Raids (not listed in [docs](https://developers.streamelements.com/endpoints/activities) but available in editor. Try implementing and test if it works)
  - [x] Subscription tiers
  - [x] Mention of new event types in the wiki

### References
[suggestion message on discord](https://discordapp.com/channels/577412066994946060/581828193196179457/625789108966391810)

**Comment by MelanX** [comment]
What's about raids/hosts?

**Comment by hlxid** [comment]
:+1:  Sure, I can also add those when I am at it anyway. StreamElements doesn't have a event for raids however.

**Comment by hlxid** [comment]
Tipeeestream implementation is done and tested using the tipeeestream event emulator with both twitch and youtube :tada:

**Comment by hlxid** [comment]
The tipeeestream implementation on the `feature/131-cheer,raid,host-event` is working from what I can tell and has been merged now. Skate will probably test the stream elements implementation together with #129, as I can't test it because the event emulator of stream elements doesn't emit fake events to the api, just to the overlay running inside the browser.
