### ISSUE TITLE
Add a OBS Connector

### ISSUE THREAD

**Issue by hlxid** [codeoverflow-org/chatoverflow#136]
### Description
A OBS connector might be very useful for live stream interaction. To control obs we can use obs-websocket, which should expose everything we could possibly need.

I think the most important things to start are
- Scene switching
- Audio level control
- Events for starting/stopping recordings/streams

If you can think of more useful functionality don't be hesitated to add a comment.

### References
The obs websocket plugin: [Palakis/obs-websocket](https://github.com/Palakis/obs-websocket/).
[Exposed functionality](https://github.com/Palakis/obs-websocket/blob/4.x-current/docs/generated/protocol.md#table-of-contents) of the plugin.
A java client: [Twasi/obs-websocket-java](https://github.com/Twasi/websocket-obs-java).

**Comment by sebinside** [comment]
That's a nice one. Would love to do that, once we're in alpha state!
