### ISSUE TITLE
Split Bootstrap Launcher into seperate repository

### ISSUE THREAD

**Issue by hlxid** [codeoverflow-org/chatoverflow#137]
### Description
We should move the bootstrap launcher to a separate repository(I would propose `codeoverflow-org/chatoverflow-bootstrap`) for clarity and also because after #101 it has gained a moderate size. `deployment-files` should also be moved to this new repository, because these files are only for the bootstrap launcher. The scripts of [codeoverflow-org/chatoverflow-setup](https://github.com/codeoverflow-org/chatoverflow-setup) need to be update to also clone this new repository.

**Comment by sebinside** [comment]
Before I create the repository: What about `chatoverflow-launcher`? More meaningful than `chatoverflow-bootstrap`?

**Comment by hlxid** [comment]
:+1: `chatoverflow-launcher` is more generic and the updater module hasn't to do anything with bootstrapping but still will be in that repository.

**Comment by hlxid** [comment]
Migrated with
* https://github.com/codeoverflow-org/chatoverflow/commit/f373cb712e1e6bf8b86379f7368705d782d18f11 
* c72d0d13dfa768ef23de2e06580d00f9a67ae3b0
* https://github.com/codeoverflow-org/chatoverflow-launcher/commit/8a280d4f6617603dcf21c68706742fdb99b80a6f
* https://github.com/codeoverflow-org/chatoverflow-setup/commit/2125f179685bd1aa7c45ac113b86d912f44b443b
