### ISSUE TITLE
Separate Framework and Api Implementation

### ISSUE THREAD

**Issue by hlxid** [codeoverflow-org/chatoverflow#138]
### Description
The implementation of the api should also get its own repository/jar to increase separation of concerns and increased plug-ability. Its also needed for the planned backwards-compatibility that we are planning.

The setup scripts have to be updated to clone the new repository and the bootstrap launcher has to be modified to not only download the dependencies of the framework jar, but also the dependencies of the api-impl jar.

### References
[backwards-compatibility plan](https://discordapp.com/channels/577412066994946060/581828193196179457/600651640181227520) by @sebinside on discord

**Comment by hlxid** [comment]
How should we name the repository which hosts the implementation? I would propose `chatoverflow-impl` or `chatoverflow-services`, I'm preferring the latter.

The connectors are required by both the framework and the implementation so we have these three options of where to put them:
1. Put the connectors in the framework and let the implementation depend on the framework
2. Put the connectors in the implementation and let the framework depend on the implementation
3. Put the connectors into a separate sbt module and let both the framework and implementation depend on it.

Option 3) would also add another jar unless sbt trickery is applied to have it as a separate module but putting the classes into the jar of the framework or implementation so I don't really like that option. 

Option 1+2) don't have any advantages or disadvantages over each other so I'm fine with either one.

**Comment by hlxid** [comment]
I think option 1 has a small advantage over option 2: we'll always have the connector class and don't have to deal with the situation that the connector class isn't available because it is in the implementation jar and no implementation jar was loaded.

Is that option and the proposed repository name fine for everyone? @sebinside @joblo2213

**Comment by sebinside** [comment]
Here are some thoughts:
- We should follow the prinicples of the onion-architecture as close as possible. This includes the stable-dependencies-principle. Dependencies should always go from outside to the inside, e.g. from the framework to the API. This would favour solution 1, as far as i understand the problem
- But: The main reason for this refactoring was the exchanability of implementations. API Implementations are somewhat coupled to the connector they work with. Following the common closure principle, these would belong in the same module which would favour solution 2

Nevertheless, this discussion shows that we should rethink how the framework shall be strucutred. This might include a discussion about dependency injection (e.g. using guice) and developing a clear structure of the different parts of a clean architecture. This would also help the testability (which is currently... non-existent).

Some more links:
https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html
https://en.wikipedia.org/wiki/Package_principles
https://en.wikipedia.org/wiki/SOLID
