### ISSUE TITLE
Don't allow empty strings as source identifiers

### ISSUE THREAD

**Issue by J0B10** [codeoverflow-org/chatoverflow#139]
### Description
It is possible to leave the sourceIdentifier field empty when adding a new connector.  
The connector will get registered but it is then not possible to delete this connector using the better REPL.  
To delete it you must edit the config.xml.

The connector with no source identifier:
> ![grafik](https://user-images.githubusercontent.com/17405009/68070951-46a91d80-fd75-11e9-8c1b-88a8b224b8f0.png)

### How to reproduce
Just add a new connector and leave the left field empty:
> ![grafik](https://user-images.githubusercontent.com/17405009/68070942-2f6a3000-fd75-11e9-88e0-f09fba926e2f.png)

**Comment by sebinside** [comment]
Done. Was also a problem in connector names and while registering.
