### ISSUE TITLE
Socket.io connector

### ISSUE THREAD

**Issue by J0B10** [codeoverflow-org/chatoverflow#143]
### Description
The Tipeeestream connector and the StreamElements connector already use socketIO but it may be beneficial to have a simple connector to listen for or emit socket events directly.

We could also use some inheritance to save a some duplicated code.

### References
socket.io client: https://github.com/socketio/socket.io-client-java

TipeeestreamConnector: https://github.com/codeoverflow-org/chatoverflow/blob/develop/src/main/scala/org/codeoverflow/chatoverflow/requirement/service/tipeeestream/TipeeestreamConnector.scala

StreamElementsConnector: https://github.com/codeoverflow-org/chatoverflow/blob/develop/src/main/scala/org/codeoverflow/chatoverflow/requirement/service/streamelements/StreamElementsConnector.scala

**Comment by sebinside** [comment]
The same applicable to the REST connector #85, as i could be a supertype for OLA #142 or AHK #140.
