### ISSUE TITLE
Create sbt task to list and save all component versions

### ISSUE THREAD

**Issue by sebinside** [codeoverflow-org/chatoverflow#146]
# Description
Chat overflow consists of a lot of components or sub projects with different version numbers. Since #118, they follow all the semantiv versioning prinicple, but are still independent. For better visibility of all versions (and better user error log, and easier deploying, ...), they should be logged at framework startup.

One approach would be an sbt task (injected into the build process), collecting all information and saving into a text file, xml file or something similar, which can be read and printed at startup.

A list of currently versioned things (probably not complete):
* Framework (sbt)
* API (APIVerison, or sbt)
* REST API (ScalaBootstrap-file)
* NPM Package (accessible trough npm command)
* GUI (accessible trough npm command)
* Other SBT artefacts (launcher, updater, build environment, bootstrap, ...?)
* And everything I did forget here :)

**Comment by hlxid** [comment]
Implemented with https://github.com/codeoverflow-org/chatoverflow/compare/d8a6b94cc13a92a9906938c2ea5178e3233408a7...2613b1d9dac4703441b619fe26460d454a9cbec7
