### ISSUE TITLE
Advanced parameters

### ISSUE THREAD

**Issue by sebinside** [codeoverflow-org/chatoverflow#151]
### Description
With #148, we now have way more parameter types. The next step would be to add advanced parameters, which can have plugin-dev defined restrictions. Some useful examples:

- [ ] Sets of possible answers, e.g. "top,middle,bottom"
- [ ] Number ranges, e.g. [5,20]
- [ ] Regex compatible input, e.g. "a*b+"

And there are probably way more usefull paramter types, so this issue can also be used to collect them all.

### References
[Subscribe to pewdiepie](https://www.youtube.com/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw)

**Comment by derNiklaas** [comment]
![image](https://user-images.githubusercontent.com/12937331/68613367-e033a600-04be-11ea-8dc1-cc3633710570.png)
Sorry, already subscribed.
