### ISSUE TITLE
Make connectors reusable

### ISSUE THREAD

**Issue by sebinside** [codeoverflow-org/chatoverflow#155]
### Description

We already discussed connector reusability, e.g. in #143. In the future, some connector will share common functionality, e.g. HTTP requests or websockets.

In order to enhance code reuse, we should discuss dependencies between connectors. Several solutions are possible:

1. connector subtyping with base connectors for basic functionality
2. common connector library classes which can be used from multiple, independent connectors
3. no reuse at all
4. ...  

Personally, I would prefer solution 2) since subtyping might introduce strong coupling which is considered harmfull for code quality

### References
Some issues with more "basic" connectors are: #143, #85, #144

**Comment by hlxid** [comment]
> common connector library classes which can be used from multiple, independent connectors

To clarify, with that you mean a class that implements functionality for e.g. websockets and then connectors which need this functionality can create as many instances of it as required and use websockets through the implementation of that class? If yes then :+1: for 2) from me.

**Comment by sebinside** [comment]
Following the rule "Composition of Inheritance", Scala Trades should be used to mix functionality in. A new Connector Inheritance Tree might not be worth the hustle.
