### ISSUE TITLE
Voice connector

### ISSUE THREAD

**Issue by derNiklaas** [codeoverflow-org/chatoverflow#159]
Cavira: 
Ein Voice Connector wäre um Funktionen anderer Twitch Bots / Stream Integrationen abzudecken auch noch ganz fancy. Vorallem der Output für donationreadings etc. darüber ob es einen Voice Input Teil auch geben sollte kann man sich streiten aber sowas wie über Voicecommands Lampen steuern (MIDI Interface?) wär schon fancy. Die Frage ist wie gesagt obs das braucht. Für den TTS Teil würd ich die Google cloud Text-To-Speech API vorschlagen. Die kann nativ mehrere Akzente ("Sprachen") und Pitches. ```https://cloud.google.com/text-to-speech/?hl=de```“

**Comment by sebinside** [comment]
english description following the issue rules please!
