### ISSUE TITLE
Resolve TODOs in the serial connector

### ISSUE THREAD

**Issue by sebinside** [codeoverflow-org/chatoverflow#29]
There are TODOs left in the SerialConnector.

This could crash:
https://github.com/codeoverflow-org/chatoverflow/blob/038eddc2b5639b39899dd137cf30ed3ad2bbcb9e/src/main/scala/org/codeoverflow/chatoverflow/requirement/service/serial/SerialConnector.scala#L54

The start method might need an actor:
https://github.com/codeoverflow-org/chatoverflow/blob/038eddc2b5639b39899dd137cf30ed3ad2bbcb9e/src/main/scala/org/codeoverflow/chatoverflow/requirement/service/serial/SerialConnector.scala#L62

This should be best resolved by @joblo2213.

**Comment by J0B10** [comment]
Does not crash, works perfectly fine. 
_All tests passed! 📗💚✅_
