### ISSUE TITLE
Saving does not work.

### ISSUE THREAD

**Issue by derNiklaas** [codeoverflow-org/chatoverflow#3]
I added an instance and then tried to save it with the "save" command.

> save
282703 21:00:55.359 [main] INFO  configuration.CredentialsService  - Found 1 credential objects to save.
282724 21:00:55.380 [main] ERROR configuration.CredentialsService  - Unable to save credentials. An exception occurred: config\credentials (Das System kann den angegebenen Pfad nicht finden)
282724 21:00:55.380 [main] INFO  configuration.ConfigurationService  - Started saving current configuration.
282730 21:00:55.386 [main] ERROR configuration.ConfigurationService  - Unable to save configuration. Exception thrown: config\config.xml (Das System kann den angegebenen Pfad nicht finden)
282730 21:00:55.386 [main] INFO  chatoverflow.ChatOverflow  - Saving took 28 ms.

**Comment by rad4day** [comment]
Also fixed in commit bf295fd4b89fffbc4cb42dcdbaa37b806d38724c
