### ISSUE TITLE
Rework stat and event input in the API

### ISSUE THREAD

**Issue by sebinside** [codeoverflow-org/chatoverflow#36]
The stat and event input seems to be unfinished and raw. Should be refactored while the implementing process of PubSub and Tipeeestream.

**Comment by J0B10** [comment]
I' have a unfinished rework of the event input laying arround.

**Comment by J0B10** [comment]
Closed in 40dac62d496e94860969ee51fcdc0b1d98295bfa / https://github.com/codeoverflow-org/chatoverflow-api/commit/19271a92dfcacfd0bc9be4cd8582fc5896be128a.
