### ISSUE TITLE
Unclear usage of TwitchChannel in the API

### ISSUE THREAD

**Issue by sebinside** [codeoverflow-org/chatoverflow#37]
The usage of the TwitchChannel (and its creation date) are unclear and should be discussed from @Renxiem and @joblo2213.

Related issue: https://github.com/codeoverflow-org/chatoverflow/issues/36

**Comment by J0B10** [comment]
It's a relikt from the old API and I never really knew what I should do with it. 
For the twitch chat serveice it's pretty unnessecary and could be removed. 
I don't know if @Renxiem does use it in it's stat api or if we really need it.
