### ISSUE TITLE
Enhance documentation

### ISSUE THREAD

**Issue by sebinside** [codeoverflow-org/chatoverflow#38]
The readme.md and wiki (incl. installation) should be updated to match the current behaviour of the software.

Additional information about connectors, actors, etc. would also be great!

**Comment by sebinside** [comment]
Idea: A new Markdown-based `chatoverflow-wiki` project where everyone can help. Way more scalable and cleaner than the github native wiki.

**Comment by J0B10** [comment]
https://labs.inn.org/2014/05/19/applying-git-to-github-wikis/ I'dd do something like that and automate the synchronization of the new collaborative wiki repo with  https://github.com/codeoverflow-org/chatoverflow/wiki by setting up a travis deploy task that automatically pushes the content from the master branch of the new repo to the codeoverflow wiki.

**Comment by J0B10** [comment]
Today I created the [codeoverflow/chatoverflow-wiki](https://github.com/codeoverflow-org/chatoverflow-wiki) repo.   
It's master branch will be automatically pushed to the [codeoverflow wiki](https://github.com/codeoverflow-org/chatoverflow/wiki).  

During the next days I will start to create a wiki page for each service, improve the old documentation, reorganize it in folders and add a custom sidbar with the contents and a custom footer that encourages contribution to the wiki and links to the discord for further support.

**Comment by sebinside** [comment]
Just a note: Travis works fine. 👍

**Comment by J0B10** [comment]
I know, it took me long enough to finaly get it working a s intended. xD

Just restructured the wiki, added a proper README to the repo and added a webhook to display all pull requests on discord. 

Do you think we need a license for the wiki?
Something more general like a creative commons ([CC-BY](https://creativecommons.org/licenses/by/4.0/) or [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/)) license as EPL is meant for code?

**Comment by J0B10** [comment]
Im currently in the process of creating detailed documentation for all services so that users can get a easy guide how to retrieve the credentials and plugin developers see how to use them.  

* [X] Twitch Chat
* [X] Discord
* [X] Serial Connection
* [x] File 
* [x] Tipeeestream

It takes quite some time to write them all, so help is apreciated!

**Comment by sebinside** [comment]
Another TODO (after the setup repo is ready): Update the installation wiki entry

**Comment by sebinside** [comment]
And two other wiki articels:
- [x] Document how we handle versioning (see comments on #118) - how and when to update
- [x] Document how we publish the npm package to the github package registry (when #133 is finished), this should include presets for the published `package.json` and the `readme.md`. The build process is currently shortly documented here: https://gist.github.com/sebinside/c6ca135f71932baf75ddc9abcbbd9bb1
- [x] Update deployment article
- [x] Add gui not found to the frequent issues

**Comment by sebinside** [comment]
Done.
