### ISSUE TITLE
Update gui license

### ISSUE THREAD

**Issue by sebinside** [codeoverflow-org/chatoverflow#39]
The gui is originally licensed under MIT. Should be checked if the relicensing under EPL is possible and then the new license should be added.

**Comment by sebinside** [comment]
Added in commit d892cf38ee3c755bb5d2aa5f25329e7dda5a0371.

**Comment by J0B10** [comment]
Just a quick tip:
Reference commits from other repos by using the url.  
https://github.com/codeoverflow-org/chatoverflow-gui/commit/d892cf38ee3c755bb5d2aa5f25329e7dda5a0371
=  `https://github.com/codeoverflow-org/chatoverflow-gui/commit/d892cf38ee3c755bb5d2aa5f25329e7dda5a0371`

See: https://help.github.com/en/articles/autolinked-references-and-urls
