### ISSUE TITLE
Rework plugin structure

### ISSUE THREAD

**Issue by sebinside** [codeoverflow-org/chatoverflow#41]
Since the beginning of version 2 of chat overflow, plugins are identified by a pluggable holding all metadata and a plugin class, holding the execution information and requirements.

This should be reworked. Pluggable should not be needed and replaced by a metadata file in the plugin jars resources. The class loader and framework could has to be updated.

**Comment by hlxid** [comment]
I would like to start working on this, but still have some questions:
1. What file format should be used? Propably xml?
2. Should multiple plugins in one jar be supported? The current code just complains, but allows it: https://github.com/codeoverflow-org/chatoverflow/blob/2cde2f93003bf007d1f6cfd6c509c3922ae620c8/src/main/scala/org/codeoverflow/chatoverflow/framework/helper/PluggableLoader.scala#L28-L32
3. Should pluggable be directly removed with pre-alpha 3 or be deprecated and slowly removed?

**Comment by sebinside** [comment]
Some ideas / notes on this:
- keep all pluggable meta data in a required xml file
- rework the PluginFramework to load this xml file (e.g. called `plugin.xml`) before loading the Plugin file
- only allow one xml and one plugin class per jar
- rework the `create` task (see issue #20) to automatically create the proposed structure with the given choice for java or scala, already containing a require for e.g. the sample connector to show the usage
- rework the `fetch` task, to only add a plugin to the `plugins.sbt` if the plugin xml file exists. Its currently a pain in the ass to delete plugins because of this
- think about other usefull (optional) fields in the xml file, e.g. a support website / source github repo or license. Maybe npm does have other usefull examples
- deprecate all other approaches. this is main reason we still call it `pre-alpha`

I hope this answers all your questions. Another spontanious idea: the plugin version could be also embeeded into the xml. Minimal sbt file changes, minimal framework reloads...

**Comment by sebinside** [comment]
Just an idea...
```xml
<plugin>
  <name>sampel</name>
  <author>sebinside</author>
  <description>Just a test</description>
  <api>
    <major>3</major>
    <minor>0</minor>
  </api>
  <version>0.4.2</version>
  <website>codeoverflow.org</website>
  <license>MIT</license>
</plugin>
```
