### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by J0B10** [codeoverflow-org/chatoverflow#55]
From my experiences [issue templates](https://help.github.com/en/articles/creating-issue-templates-for-your-repository) really improve the quality of bugreports and feature requests.

We could also use them to give our todos a uniform layout.

**Comment by derNiklaas** [comment]
Maybe even add all of those templates.
https://github.com/codeoverflow-org/chatoverflow/community

**Comment by J0B10** [comment]
I don't really like the ones form Github. They are way to generic. 
And I don't really see a need for a Code of Conduct or a Contributing guideline.

**Comment by sebinside** [comment]
If you are experienced, you're welcome to add a template! (I'm a noob, lol)
