### ISSUE TITLE
RCON Connector 

### ISSUE THREAD

**Issue by J0B10** [codeoverflow-org/chatoverflow#62]
### Description

A connector that allows remote control of services & games by using the _Source RCON Protocol_, especially executing commands inside minecraft and receiving the response.

This would allow triggering actions ingame from the codeoverflow framework, but is limited to executing the commands and receiving the responses.  
It wouldn't allow getting the ingame chat or the console output.
Furthermore reacting to ingame commands is also not possible.

### References

Documentation of the protocol (valve):   _https://developer.valvesoftware.com/wiki/Source_RCON_Protocol_

Documentation of the protocol (minecraft): _https://wiki.vg/RCON_  

Possible library: _https://github.com/Kronos666/rkon-core_

**Comment by strifel** [comment]
I will try this.

Edit (26 June): I have a first working version by now, which can send a command to the server

Edit (27 June): https://github.com/codeoverflow-org/chatoverflow/pull/68

**Comment by J0B10** [comment]
>###  Fragmentation
> 
> Maximum C->S packet payload length: 1446 (total: 1460) - outdated?
> 
> Maximum S->C packet payload length: 4096 (total: 4110)
> 
> The minecraft server can fragment responses across multiple packets. There's no simple way to know when the last response packet has been received; approaches include:
> 
>1. Wait until we receive a packet with a payload length < 4096 (not 100% reliable!)  
>
>2. Wait for n seconds  
>
>3. Send two command packets; the second command triggers a response from the server with the same Request ID, and from this we know that we've already received the full response to the first command.
>The second packet should use a command that will not produce fragmented output
>An alternative is for the second C->S packet to use an invalid type (say, 100); the server will respond with a 'Command response' packet with its payload set to 'Unknown request 100'.
>
> _origin: [wiki.vg/RCON](https://wiki.vg/RCON#Fragmentation)_

I want to test with various games, comands & servers if this has an big impact or if it is negligible.  
Building a workaround for this sounds pretty complex, given that it has to work with different games.  

Thats why I'dd delay testing and megrging this pr.

Other than that it's looking good, great work 👍

**Comment by strifel** [comment]
I thought this was not used often enough.
I can only imagine using `/list` on a big Minecraft server.

But this could actually cause a problem with the next command getting the wrong response. I will try to at least fix this.
I will also try if I can implement the first workaround because this seems fairly easy.

**Comment by J0B10** [comment]
For the default minecraft commands it shouldn't have an Impact, the returned responses are way too short for that.

So currently there is not really a need for this.

What I want to test before merging is how big the returend responses may be...

**Comment by J0B10** [comment]
Created a simple plugin for testing, I will start to test this evening.

https://gist.github.com/joblo2213/833d0621aa160a00f76eb888f60ed799/

**Comment by J0B10** [comment]
Implemented basic tests in the testall plugin for the rcon connector: [`feature/62-rcon`](https://github.com/codeoverflow-org/chatoverflow-plugins/tree/feature/62-rcon)
