### ISSUE TITLE
Add bash scripts for framework setup

### ISSUE THREAD

**Issue by sebinside** [codeoverflow-org/chatoverflow#63]
### Description
As mentioned from Gerd, there should be bash / bat scripts for windows, mac os and unix to setup the development environment.

First, it should be tested if sbt, git and npm are installed. Then, all steps from the setup guide should be emulated, including the sbt commands. This would leave a ready-to-open project for IntelliJ.

TODOs:
- [x] install script for bash (*nix systems)
- [x] bat install script for windows
- [x] Support for a `--dev`-option to check out the `develop` branch directly
- [x] Discuss, if executing the steps from the `[Advanced]`-run is an additional / good idea
- [x] Update the wiki

### References
Setup guide: https://github.com/codeoverflow-org/chatoverflow/wiki/Installation
Setup repository: https://github.com/codeoverflow-org/chatoverflow-setup

**Comment by justgerd** [comment]
I have written up a WIP bash script in a gist: https://gist.github.com/gerd2002/25d9e182c5c0baace221a9c48cd1d6e9

**Comment by sebinside** [comment]
Added setup repo: https://github.com/codeoverflow-org/chatoverflow-setup

**Comment by sebinside** [comment]
First script works fine, updated TODOs.

**Comment by justgerd** [comment]
Updating the wiki should probably be added to the TODO list

**Comment by J0B10** [comment]
I'll have a look at the wiki and at the same time try to add the -dev option as I now have some experience with shell (from creating the scripts for travis). 

**Last open point:**

> * [ ] Discuss, if executing the steps from the [Advanced]-run is an additional / good idea

Maybe as another option? `--advanced`?

**Comment by J0B10** [comment]
`--dev` options have been added to both scripts and tested under linux and windows. 
Somebody still needs to test it under MacOS

**Comment by sebinside** [comment]
Maybe... `--build`? I will test it on macos

**Comment by J0B10** [comment]
Niklas tested `--dev` on MacOS
