### ISSUE TITLE
Can't set credentials 

### ISSUE THREAD

**Issue by derNiklaas** [codeoverflow-org/chatoverflow#69]
### Description

When I try to add an entry to a credential, the GUI gives me the following Error: 
![image](https://user-images.githubusercontent.com/12937331/60401276-0e9f8d00-9b7f-11e9-86be-84e9bd5e43dc.png)

### How to reproduce
1. Create a credentials object
2. Try to add an entry

### Error Log 
 
No Error Log

**Comment by sebinside** [comment]
So, every project (main, api, gui) on master branch and updated? `sbt gui` executed after this?

**Comment by sebinside** [comment]
Just tested it with `SampleConnector` and `TwitchChatConnector` without problem.

**Comment by derNiklaas** [comment]
Selbst nachdem ich manuell in jedem relevanten Ordner git pull eingegeben habe, funktioniert das trotzdem nicht (auch nachdem ich sbt gui eingegeben habe
![image](https://user-images.githubusercontent.com/12937331/60402355-aeb0e280-9b8e-11e9-9045-90f1e3b56270.png)

**Comment by sebinside** [comment]
Probiere bitte folgendes:
- Login über die Better REPL, Auth Key kopieren
- Den Petstore Link öffnen, die Funktion postCredentialsEntry mit dem kopieren AuthKey und den anderen Daten füttern

Wenn das funktioniert: In der Konsole in den gui Ordner wechseln und via `ng serve` bzw. `npm run start` die GUI manuell starten und via localhost:4200 die eingabe, die zum fehler geführt hat wiederholen

**Comment by sebinside** [comment]
Oh und um noch einen ganz üblen Verdacht auszuräumen: Du hast nicht zufällig versucht, einen Connector zu bearbeiten, den du nicht über die GUI sondern noch über die alte REPL erstellt hattest?

**Comment by derNiklaas** [comment]
Zu deinem zweiten Kommentar: 
Nein, das ist ein völlig neue Instance mit neuem Connectoren

Edit: Habe auch gerade eine neues Credentials Objekt erzeugt und dort (in der gleichen season) versucht, eine Entry hinzuzufügen, welches auch nicht funktioniert hat

**Comment by sebinside** [comment]
Das ist schräg... @joblo2213 hatte auch 0 probleme beim testen vorhin, wir bekommen den fehler mit den infos nicht repliziert. bin gespannt, was beim ersten kommentar rauskommt

**Comment by derNiklaas** [comment]
Zu deinem ersten Kommentar:
Ich habe es gerade getestet und habe die selbe Fehlermeldung bekommen.

**Comment by derNiklaas** [comment]
Soll ich evtl. mal den Config ordner neu generieren lassen?

**Comment by sebinside** [comment]
Ja, du kannst ja auch einfach per CLI einen anderen (neuen) Ordner als config auswählen

**Comment by derNiklaas** [comment]
Selbst nachdem ich den Config Ordner neu generiert habe, kommt der gleiche Fehler raus. 
Hast du weitere Ideen, was man da machen kann/soll?

**Comment by sebinside** [comment]
Ansonsten kannst du mal im `ConnectorController` bei der Methode `decryptCredentialsValue` einen Breakpoint setzen. Hier wird der mit dem Client-AuthKey verschlüsselte Wert mit dem Server-AuthKey entschlüsselt. Und wenn richig kommuniziert, sollten beide Keys auch übereinstimmen.

**Comment by derNiklaas** [comment]
Der Authkey der in der GUI steht ist der gleiche, welcher auch via chatOverflow.credentialsService.generateAuthKey() zurückgegeben wird.

Es wird jedoch eine Exception in CryptoUtil.decryptSSLcompliant geworfen. 

EDIT: Um genauer zu sein: java.security.InvalidKeyException: Illegal key size

**Comment by sebinside** [comment]
Omg... Update bitte mal deine Java jdk 😂

**Comment by sebinside** [comment]
Hier wurde das "Problem" gut zusammengefasst: https://blog.doubleslash.de/jce-unlimited-strenght-cryptography-ab-jetzt-standardmaessig-aktiv/

**Comment by sebinside** [comment]
Und möchtest du mir die genaue Zeile des errors schicken? Dann Bau ich eine Fehler Meldung für zukünftige Generationen von Nutzern veralteter Versionen ein 😁

**Comment by derNiklaas** [comment]
Der Fehler ist in Zeile 57 ( https://github.com/codeoverflow-org/chatoverflow/blob/master/src/main/scala/org/codeoverflow/chatoverflow/configuration/CryptoUtil.scala#L57 ). 

Da man das JDK für Java 8 nur mit einem Oracle Account Downloaden kann, werde ich nachher mal Java ~~10~~ 12 testen dürfen 😅

**Comment by derNiklaas** [comment]
Habs mit Java 12 getestet und nun funktioniert es auch.

**Comment by derNiklaas** [comment]
Reopened because skate.

**Comment by sebinside** [comment]
Added warning in commit d81d4b0396d50a47a9e6b9f5ee3afcb0e1de4a7d. Closed forever (hopefully).
