### ISSUE TITLE
Improve plugin log

### ISSUE THREAD

**Issue by J0B10** [codeoverflow-org/chatoverflow#74]
### Description
The plugin log is currently pretty annoying to read.  
From my point of view we really need the following stuff to improve it:

- [x] Start a new line after each log message in the gui
- [x] Automatically update the log messages in the gui if there are new messages
- [x] Also output them to the framework log

### References
_none_

**Comment by J0B10** [comment]
outputting log to framework log can already be done by using `-o` flag in cli.
https://github.com/codeoverflow-org/chatoverflow/blob/1f6e0f70483a5b551a6d6c2489ac42c825aa24c0/src/main/scala/org/codeoverflow/chatoverflow/ui/CLI.scala#L37-L38

**Comment by sebinside** [comment]
Everything is already implemented and reviewed in #78. When finished, this will close #74.
