### ISSUE TITLE
Discord Connector: Massive Performance Issues

### ISSUE THREAD

**Issue by sebinside** [codeoverflow-org/chatoverflow#76]
### Description
After a short amount of time, the memory and cpu load of the discord connector explodes. This happened after 10-30 messages from different users, recorded with this code:

```scala
discordInput.get().setChannel("285809306790789120")
    discordInput.get().registerChatMessageReceiveEventHandler(
      event => log(s"[D] ${event.getMessage.getAuthor.getDisplayName}: ${event.getMessage.getMessage}"))
```

On my machine, it took up to 90% cpu and over 18 GB of RAM and completely stopped working, did not respond to newer messages.

![explosion](https://user-images.githubusercontent.com/7331248/60768617-439f6880-a0c6-11e9-84b2-632b3a275a62.PNG)

The profiler shows a huge leak in recorded char arrays / strings. I don't know why this did not came up earlier, but it is a problem :D

![profiler](https://user-images.githubusercontent.com/7331248/60768623-692c7200-a0c6-11e9-9aed-e5e5d3acda17.PNG)

### How to reproduce
I created a discord bot, joined on a server, configured the connector with the given credentials and executed the code above in a plugin. It took less then a minute to stop working, but worked fine initially.

### Error Log 
There is no exception thrown, it just stops working.

**Comment by RodneyMKay** [comment]
This ist most likely caused by the while-loop in org.codeoverflow.chatoverflow.requirement.service.discord.impl.DiscordChatInputImpl line 316. You probably want to change the arguments of the call to String.indexOf inside the loop to contain the last index. That would lead to the index variable actually updating so that the while-loop can end.

**Comment by sebinside** [comment]
This was the solution. Thanks @RodneyMKay!
