### ISSUE TITLE
setChannel doesn't work correctly

### ISSUE THREAD

**Issue by MelanX** [codeoverflow-org/chatoverflow#80]
### Description
Der Channel wird scheinbar nicht richtig gesetzt. Denk ich. Kenn mich da nicht so gut aus :D

### How to reproduce

https://gist.github.com/MelanX/898acdc9f0734efa05b017ddda484b0b
Ich habe das als Beispiel. Wenn man den sleep in Zeile 11 und 13 entfernt, wird der Bot nicht auf Nachrichten reagieren.

Der Teil vom Code, wo der Fehler hauptsächlich stattfindet (I guess)
```
val channel = "#skate702"
Thread.sleep(500)
twitchChatInput.get().setChannel(channel)
Thread.sleep(500)
twitchChatOutput.get().setChannel(channel)
```

**Comment by hlxid** [comment]
Nach testen neben dem Coding-Stream denke ich, dass das Problem darin besteht, dass das Framework wartet bis sich der Bot verbindet und dann das Plugin startet. Es wartet aber nicht bis der Bot sich authentifiziert. Das Plugin will in den Channel, kann es aber nicht, weil der Bot je nachdem sich vielleicht noch anmeldet. Ich werde morgen nochmals genau testen und gegebenenfalls zusammen mit #27 fixen.

**Comment by J0B10** [comment]
Fixed in `0.2.1-prealpha`.
