### ISSUE TITLE
REST Input /Output 

### ISSUE THREAD

**Issue by derNiklaas** [codeoverflow-org/chatoverflow#81]

**Comment by J0B10** [comment]
Please provide at least a short description!

**Comment by promasu** [comment]
![image](https://user-images.githubusercontent.com/23510137/60987211-6be6cb80-a341-11e9-9f3d-ae93219a5696.png)     ![SCHULD](https://cdn.discordapp.com/emojis/499297818582843392.png?v=1)

**Comment by sebinside** [comment]
Replaced by #85, which is more specific.
