### ISSUE TITLE
Sandbox beahviour unclear

### ISSUE THREAD

**Issue by J0B10** [codeoverflow-org/chatoverflow#84]
### Description
It seems like the sandbox isn't working properly. I wanted to do some testing for #33 to see when reflection kicks in and the sandbox causes a Security Exception, but it never happened...
Therefore I added a simple check using refelection to check if the sandbox is actually active: 
 ```scala
    try {
      classOf[jsontest].getFields
      log("Sandbox isn't working")
    } catch {
      case _: SecurityException => log("Sandbox is working")
    }
```
[_--> goto file_](https://github.com/codeoverflow-org/chatoverflow-plugins/blob/fb549de1c43293053c65c1dd7e40e079f3c74c0a/testall/src/main/scala/org/codeoverflow/plugins/testall/tests/jsontest.scala#L31-L36)

**The method was executed without throwing a security exception!!!**
 
### How to reproduce
1. Checkout the [`junk/33-json4s-sandbox-test`](https://github.com/codeoverflow-org/chatoverflow-plugins/tree/junk/33-json4s-sandbox-test) branch in public-plugins.
2. Run the testall plugin
3. Have a look at the log

### Error Log 
https://gist.github.com/joblo2213/9076a79c5634ae4fe99fe770e085b803

### References
**Used versions:**  
https://github.com/codeoverflow-org/chatoverflow/commit/130e2ab626d3f4ce65c256dc01a4a374004d0660  
https://github.com/codeoverflow-org/chatoverflow-api/commit/b2b5d6797496ee69a865b0af42b06126ffbe5d42  
https://github.com/codeoverflow-org/chatoverflow-gui/commit/7ed0530e7f31fc35515e9a30f72083fcc68653b8  
https://github.com/codeoverflow-org/chatoverflow-plugins/commit/fb549de1c43293053c65c1dd7e40e079f3c74c0a

**Comment by J0B10** [comment]
I added a web request to the check to see if that violates the sandbox (https://github.com/codeoverflow-org/chatoverflow-plugins/commit/42093dbfbfdb01228e3b36c105eb9272cfd0d5e2):  
```scala
    try {
      classOf[jsontest].getFields
      log("Reflection read access is possible")
      val s = Source.fromURL(new URL("https://gist.githubusercontent.com/joblo2213/9076a79c5634ae4fe99fe770e085b803/raw/c3dae1c47888ce522cb68b133a05a3091d394a8e/jsontest.log"))
      s.mkString
      s.close()
      log("Web requests are working")
      log("Sandbox is totally broken!!!")
    } catch {
      case _: SecurityException => log("Sandbox is working")
    }
```

**Result:**
```
16345 09:37:53.970 [Thread-30] INFO  manager.PluginManagerImpl  - [testall] json test: testing
18553 09:37:56.178 [Thread-30] INFO  manager.PluginManagerImpl  - [testall] [json test] Reflection read access is possible
18604 09:37:56.229 [Thread-30] INFO  manager.PluginManagerImpl  - [testall] [json test] Sandbox is working
```

So it seems like web requests are prohibited by the sandbox but reflection read access isn't.
So bigger security issues are prevented. 😅 

**We need to do some extensive testing what is prevented by the sandbox and what is prohibeted to make sure this doesn't introduce some vulnerabillities!**

**Comment by sebinside** [comment]
This thread does explain the problem. Reflection is not deactivated by default, only access considered dangerous (e.g. reading private fields) is forbidden. We could deactivated the complete reflection integration, but considering the json4s functionality, this might bring more new problems than solving (non existent) security problems.

https://stackoverflow.com/questions/40218973/java-security-manager-completely-disable-reflection

**Comment by sebinside** [comment]
Cite: `Yes, it is not called for getDeclaredMethods(), but if you want to access private/protected methods via Method.setAccessible(true) the SecurityManager is called.`

Is this issue solved with this?

**Comment by J0B10** [comment]
Seems to be resolved.
