### ISSUE TITLE
REST Input/Output & Http Output

### ISSUE THREAD

**Issue by sebinside** [codeoverflow-org/chatoverflow#85]
### Description
There should be an easy way to registern REST-like API interfaces for plugins in a separate scope then the global API. Connector support and input should be declared. A http output is another idea.

### References
This issue replaces #81, which was not specific enough.

**Comment by strifel** [comment]
I like the Idea of an http connector.
This could be a connector which gets a regex scheme of a url the plugin can access, to not allow full internet access?

**Comment by J0B10** [comment]
Or just a list of base urls.
I think its better to make controlling such security relevant stuff as easy as possible.

**Comment by sebinside** [comment]
Why controlling it at all? Who should specify, which web requests are OK? I don't see the clear vulnerability of get and post requests, when we have code execution disabled.

**Comment by sebinside** [comment]
As mentioned in #143, could be a super type for http communication, e.g. for OLA #142 or AHK #140.
