### ISSUE TITLE
Host java- and scaladoc on Github Pages

### ISSUE THREAD

**Issue by J0B10** [codeoverflow-org/chatoverflow#92]
### Description
I'dd like to suggest that we host the scaladoc for the framework and the javadoc of the api on github pages and keep it up to date with the master branch, so that plugin developers can easily use it and we can reference it on github pages.  

Github Pages has the advantage over hosting on a private webserver that every contributor with push acces to the repo can update the documentation by pushing to the `gh-pages` branch.  

It also allows everybody to create a local copy by just cloning the branch.

**I'dd do the following things:**

* [x] Deploy the docs to github pages.
* [x] **(Optional)** _Setup travis to auto generate the docs and push them_

**@sebinside could do:**

* [x] make sure Github Pages is activated and configured to use the `gh-pages` branch in the [project settings](https://github.com/codeoverflow-org/chatoverflow/settings)
* [x] add a custom domain to github pages (maybe [docs.codeoverflow.org](https://docs.codeoverflow.org)?)

### References
https://pages.github.com/
https://help.github.com/en/articles/using-a-custom-domain-with-github-pages

**Comment by J0B10** [comment]
As it's now automated via travis there is no need for a sbt task.

Repo can be found under https://github.com/codeoverflow-org/chatoverflow-gh-pages

**Comment by sebinside** [comment]
Last open todos:
- [x] create a readme.md
- [x] create a simple index.html
