### ISSUE TITLE
Update node-sass to 4.12.0

### ISSUE THREAD

**Issue by strifel** [codeoverflow-org/chatoverflow#93]
### Description
When using a node-sass version below 4.12.0 this will cause errors (installing and building the gui) on some systems (including mine).
The only working fix I found is updating node-sass with `npm install node-sass@4.12.0`.
Then I am able to build again.

### References
There is a [StackOverflow Question](https://stackoverflow.com/questions/55973930/yarn-node-sass-does-not-yet-support-my-current-environment) which has the same problem (and same fix). So this could be relevant for multiple people.

**Comment by sebinside** [comment]
It already was updated in the `develop` branch, I updated it in the `master` as well.
