### ISSUE TITLE
Escape plugin names in plugins.sbt

### ISSUE THREAD

**Issue by sebinside** [codeoverflow-org/chatoverflow#94]
### Description
We could use the backtick-notation to enable more plugin naming possibilities. e.g. naming a plugin `private` causes an error in the `plugins.sbt` right now. This might also solve the hyphen-problem.

**Comment by sebinside** [comment]
Probably interesting for @daniel0611 :D

**Comment by hlxid** [comment]
Will pr it sometime today. Note that java doesn't provide a way to escape class names, meaning we also need to filter out illegal characters anyway like I did in ff66784b8c9e5f5bfe8ffc984bf3d225cadc3282 for hyphens. Still a valid fix for keywords though.
